CREATE TABLE dbo.Selo
(
	Id			INT				NOT NULL CONSTRAINT PK_IdSelo PRIMARY KEY,
	Descricao   VARCHAR(250)    NOT NULL
);

ALTER TABLE dbo.Jogo ADD Descricao VARCHAR(300) NULL;
ALTER TABLE dbo.Jogo ADD IdSelo INT NULL;
ALTER TABLE dbo.Jogo ADD Imagem VARCHAR(MAX) NULL;
ALTER TABLE dbo.Jogo ADD Video VARCHAR(MAX) NULL;

ALTER TABLE dbo.Jogo ADD CONSTRAINT FK_IdSelo FOREIGN KEY (IdSelo) REFERENCES Selo(Id);
